language: 
    - java
jdk:
  - oraclejdk8

install:
  - cd /home/travis/build/SujataDarekar/MavenUnittestRepo/Source/bw6-maven-plugin
  - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
 - mvn clean
 - mvn compile
 - mvn test
  
